version: '3'

tasks:
  install-cargo:
    cmds:
      - curl https://sh.rustup.rs -sSf | sh
  export-web:
    cmds:
      - cargo build 
        --release 
        --target wasm32-unknown-unknown
      - wasm-bindgen 
        --out-name bloons 
        --out-dir ./out/game/ 
        --target web 
        ./target/wasm32-unknown-unknown/release/bloons.wasm
      - cp -r assets out/
      - cp -r web/ out/
    silent: true
